repo_url: "https://github.com/warllemedicao/Voz_styllett2.git"
repo_dir: "/content/Super_voz"
project_subdir: "super_Voz"

styletts2_repo: "https://github.com/yl4579/StyleTTS2.git"
styletts2_dir: "/content/drive/MyDrive/StyleTTS2"

# Configuração do Cloudflare R2 (S3-compatible)
cloudflare_r2:
  endpoint_url: ""
  access_key_id: ""
  secret_access_key: ""
  bucket_name: "super-voz"
  raw_audio_prefix: "super_voz/Audios_Brutos/"
  # processed_audio_prefix: "super_voz/Audios_processados/" # REMOVIDO PARA FORÇAR LIMPEZA IA COMPLETA
  output_prefix: "super_voz/super_Voz_outputs/"

raw_audio_candidates:
  - "Audios_brutos"

# processed_audio_candidates: # DESATIVADO PARA GARANTIR QUE limpeza_ia.py RODE SEMPRE
#   - "Audios_processados"

speaker: "0"
sample_rate: 24000
val_ratio: 0.05
phonemize: true
phonemizer_language: "pt-br"

# Configuração segura para Colab/T4 15 GB.
# Ajustes rigorosos contra CUDA Out of Memory.
epochs: 50
batch_size: 2
max_len: 128
save_freq: 1
log_interval: 10

# Mantém a fase SLM adversarial desativada no Colab comum.
joint_epoch: 999
diff_epoch: 10

# Mesmo com joint_epoch alto, deixamos estes valores seguros se você ativar SLM depois.
batch_percentage: 0.0625
slm_min_len: 100
slm_max_len: 150

# Filtro de segurança do dataset para evitar amostras/transcrições longas demais.
# O limite de 8 a 10 segundos é fortemente recomendado para T4 (15GB).
max_audio_seconds: 10
max_text_chars: 200
